version: "3"
services:
  mongo:
    hostname: mongo
    image: "mongo:latest"
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      productcart_net:
        ipv4_address: 172.19.241.2
  swagger-ui:
    hostname: swagger-ui
    image: "swaggerapi/swagger-ui"
    volumes:
      - ".:/tmp"
    ports:
      - "4100:8080"
    restart: always
    environment:
      - SWAGGER_JSON=/tmp/swagger.yml
    networks:
      productcart_net:
        ipv4_address: 172.19.241.3
  productcart-server:
    build:
      context: .
    container_name: productcart-server
    ports:
      - "3000:3000"
    volumes:
      - "./logs:/usr/src/productcart/logs/"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_HOST=172.19.241.2
      - MONGO_PORT=27017
      - MONGO_DB=prodserver
    restart: always
    networks:
      productcart_net:
        ipv4_address: 172.19.241.4
networks:
  productcart_net:
    external: true
