export const CONSTANTS = {
  PERCENTAGE: 'percentage',
  FIXED_AMOUNT: 'fixed_amount',
  FIXED_AMOUNT_DEPENDENT_SKU: 'fixed_amount_dependent_sku',
};

export const ROUTES = {
  PRODUCTS: '/products',
  CHECKOUT: '/checkout',
};

export const PRODUCTCART_PRODUCTS_REQUEST = 'PRODUCTCART_PRODUCTS_REQUEST';
export const PRODUCTCART_PRODUCTS_REQUEST_SUCCESS = 'PRODUCTCART_PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTCART_PRODUCTS_REQUEST_FAILED = 'PRODUCTCART_PRODUCTS_REQUEST_FAILED';
export const PRODUCTCART_CHECKOUT_REQUEST = 'PRODUCTCART_CHECKOUT_REQUEST';
export const PRODUCTCART_CHECKOUT_REQUEST_SUCCESS = 'PRODUCTCART_CHECKOUT_REQUEST_SUCCESS';
export const PRODUCTCART_CHECKOUT_REQUEST_FAILED = 'PRODUCTCART_CHECKOUT_REQUEST_FAILED';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const API_ENDPOINTS = {
  BASE_URL: `http://${window.location.hostname}:3000/api/v1`,
};
